# Project
site_name: 'vegardhw.net'
site_description: 'Technical ramblings and other stuff'
site_author: 'Vegard Hoff Walmsness'
site_url: https://www.vegardhw.net

# Repository
repo_name: www.vegardhw.net
repo_url: https://github.com/vegardhw/www

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros
  - mkdocs-video
  - tags
  - blog:
      blog_dir: techtalk
  - blog:
      blog_dir: outdoorstalk

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - footnotes
#  - lightgallery
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #    options:
  #      custom_icons:
  #        - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

extra:
  social:
    - icon:  fontawesome/brands/twitter
      link:  https://twitter.com/vegardhw
    - icon:  fontawesome/brands/github
      link:  https://github.com/vegardhw
#    - icon:  fontawesome/brands/slack
#      link:  https://someone.slack.com
    - icon:  fontawesome/solid/envelope
      link:  mailto:vegardhw@mail.com

nav:
# - TechTalk:
#   - techtalk/index.md
  - 💻:
    - index.md
    - macOS:
      - guides/macos/basic-config.md
#     - guides/macos/terminal-basics.md
      - guides/macos/third-party-apps.md
    - Linux:
      - guides/linux/index.md
    - Windows:
      - guides/windows/index.md
  - 📸:
    - photography/index.md
#  - OutdoorsTalk:
#    - outdoorstalk/index.md
  - ℹ️: about.md

theme:
  name: material
  custom_dir: docs/theme_override_up42
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
#    - navigation.tracking
#    - navigation.tabs.sticky
#    - navigation.expand
#    - toc.integrate
  logo: https://am3pap006files.storage.live.com/y4mt5MG90rCFHX5zpfBer-sC_osV7XARnYuqUC9LSz7QPUQovBRSsLL5JlToJsRGRRAwDFiiwnGATo6c89QKpMNtzoPQ2XJO05MRBjCuGmoVrmXEQt4OTQJbGaMsqBKUkIpbsyTgxrkpkamxF9QM8JBdEwYx43p1r8pjoQnCun-nknMx17VQ1-u5rRWY_pLeaP4?width=421&height=421&cropmode=none
  favicon: https://asite.com/alogo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        # icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      # primary: purple
      # accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        # icon: material/toggle-switch
        name: Switch to light mode
      # primary: purple
      # accent: amber
extra_css:
  - stylesheets/mkdocs.css
  - https://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin